### ISSUE TITLE
Web User Dashboard

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [TheMaverickProgrammer/OpenNetBattle#13]
For the API right now we need:
- A way for users to sign up and have an account 
  - ~While JWT tokens are fine, I cannot read them from the web browser in the engine. Let's discuss other authentication possibilities~ using HTTP cookies for sessions
- Folder api endpoint ✔️ 
  - Folders are just names to a list of available chips so they need two fields: ID, NAME
  - e.g. `localhost/folders` -> returns json of collections ` { {name: "TestFoldr", id: 1}, {name: "PVPFoldr", id: 2}, ... }`
  - Query the folder returns the chip list of UUIDs e.g. `localhost/folders/2` -> `{ name: "PVPFolder", id: 2, chips: [478434838, 349394343, ... ] }`
    - The uuid field will be used to query the Chip API endpoint next
- Chip api endpoint ✔️ 
  - Chips have letter codes, display damage (on the front end `0` display damage should be replaced with `N/A` or similar), primay element type, secondary element type, support boolean (true or false), chip description, long description (like a help manual to use the chip), an associated chip image (PNG), an icon image (PNG), name, and a UUID
     - The chip image (card) can only be 56x48
     - Chip icon can only be 14x14
     - Chips will also need to have a field for the script location (later in 2020: ideally at the media.battlenetwork.io endpoint). This field will go unused at first until scripting is finished in 2020.
     - Query the chip returns its data e.g. `localhost/chips/478434838` -> ` { name: "Cannon", codes: ['A', 'B', 'C', '*'], damage: 40, element: "None", secondaryElement: "None", description: "Attack across the field", verboseDescription: "Use A to fire a cannon.\nLasts for 3 frames.\nChips are A,B,C", image: "media.battlenetwork.io/chips/Cannon.png", icon: "media.battlenetwork.io/chips/Cannon.ico.png", uuid: 478434838 }`

The front end should be simple and list the chips off in a cool way. The list/table should:
- sort by all the fields listed previously
  - Sorting by icons/images is not possible
- Allow you to add/remove as many as you want from the global chip library (that's why we need UUIDs for chips)

You can:
- Create, Rename, Edit, Delete, Copy, and Share Folder
- Edit folder takes you to the Folder's screen that lists all the chips. In my mind it would be cool to make a chip widget that has the chip card image and battle info with a little copper plate at the bottom of the widget (like a real battle chip). You can select/deselect and delete them here. Some sort of "Add" button. Clicking this takes you to the global chip screen where you can select the chips to move to your folder.
  - The global chip screen is just like the chip list for the user but has ALL the chips ever uploaded **and** approved
     - Note: since only admin accounts can upload new chip content, they should be auto-approved by admin accounts at this time.
- Share folder generates a public URL to the READ-ONLY folder that people can click IMPORT and automatically import the folder to their list of folders.

Users are divided into two:
- Regular ✔️ 
- Admin (us) ✔️ 

Admin has an extra portal to add new chips and upload associated scripts for them. (Later in 2020 everyone can create a chip and submit but Admin will be the ones to approve/reject chips.)

Keep it very simple 😎 We just want functionality at this time - so that the engine can communicate with it and users can manage their collection of chips. Any extra aesthetic can come later if you're short on time.

**Comment by NetOperatorWibby** [comment]
## A way for users to sign up and have an account
When users sign up they can be presented with a code. They then have `x` amount of time to enter that code in the engine to both verify their account and/or login.
- If their email address is in the database already, just log them in
- If their email address is _not_ in the database, create an account

## Folder API endpoint
For the chip list, why not store the UUIDs into an array by themselves instead of creating objects with a `uuid` key?

So instead of `localhost/folders/2` returning:

```
{
  name: "PVPFolder",
  id: 2,
  chips: [
    {
      uuid: 478434838
    }, {
      uuid: 349394343
    },
    ...
  ]
}
```

It will return

```
{
  name: "PVPFolder",
  id: 2,
  chips: [
    "478434838",
    "349394343",
    ...
  ]
}
```

## Chip API endpoint
- I think `damage` should always be returned, even if it is `0`. Keeps the API consistent and you won't have to check in a chip has that key.
- A `type` key should be added to chips. Here are a few I can think of:
  - attack
  - drain
  - field
  - heal
  - support
- Some chips can have more than one type:
  - Anubis: drain and field (or I may be thinking of the Program Advance...)
  - Roll: attack/drain and heal

So it sounds like this project involves an API and a UI. Where is the data the API will draw from?

**Comment by TheMaverickProgrammer** [comment]
Good points about returning uuids only.
I like the "session code" idea. Works for me.
Damage will always return - I meant that for the table results maybe a `-`
to represent N/A would be present in the field instead of 0 to avoid
confusing players about the actual damage.
Type is kind of the same as Elements which is represented as a string.
Elements are here:
https://github.com/TheMaverickProgrammer/battlenetwork/blob/feature/v2/BattleNetwork/bnElements.h
"SIZE" isn't an element. It helps determine the length of the enum type in
C++.
Recently I've been informed from a fan on TeamBN that chips have 2
elements. I'll modify the requirements to represent 2 elements.

The data will be from a database. I'll write the database schema,
configure, and send the URL via email from where you can test from.

**Comment by TheMaverickProgrammer** [comment]
Today I finished the API. Since I ended up writing it, I used passport and HTTP session handling via cookies. The user can optionally supply an email so we can do password recovery later. Once logged in, the HTTP requests can be made to POST, GET, PUT, and DELETE records. I read and store this cookie in the engine-side too.

I'll host the API on a server tomorrow and email you a test user account along with all the available endpoints that your front end will need to use.

**Comment by NetOperatorWibby** [comment]
Sounds good!

**Comment by TheMaverickProgrammer** [comment]
Sent an email with the credentials and URL endpoint. 

I forgot to mention: importing folders is a 2-step process:

When you're previewing a "public folder", you can submit (POST) all the folder data to the `/folders` endpoint and that will create an identical folder for the currently signed-in user.

**Comment by NetOperatorWibby** [comment]
The repo for the UI will be here: https://github.com/NetOperatorWibby/battlenetwork-ui.

Gonna make some updates this week.

**Comment by TheMaverickProgrammer** [comment]
Awesome! I will have updates too but I won't change anything to the live api. It will be small changes that will be easy to add to your existing calls.

**Comment by NetOperatorWibby** [comment]
Is the admin folder supposed to be empty? Also, I pushed updates to my repo. No UI is implemented, I just wanted what I had thus far pushed already.

**Comment by TheMaverickProgrammer** [comment]
Yes it shouldnt be usable but I may change that. Admin was for app
permissions like your UI and my c++ web client. So an app cant
"technically" have chips and stuff.

To test users, use the admin account to create a test user. Then you can
sign in as the user and create folders and add chips.

Ill look at it when I get home tonight. 👌

**Comment by NetOperatorWibby** [comment]
Ah okay, I'll do that.

**Comment by TheMaverickProgrammer** [comment]
The C++ half of the web client step is code-complete. Once we can test and verify results across the dashboard we'll consider it feature complete.

**Comment by TheMaverickProgrammer** [comment]
I have made a working dashboard

**Comment by NetOperatorWibby** [comment]
My apologies for not getting this out in a timely manner. Life.

**Comment by TheMaverickProgrammer** [comment]
If you ever want to take a crack at redoing the CSS be my guest. Mine is not mobile friendly. 😬
