### ISSUE TITLE
[Linux] Project builds but is unable to run

### ISSUE THREAD

**Issue by 78Alpha** [TheMaverickProgrammer/OpenNetBattle#195]
The engine builds with some changes (Using Clang instead of GCC/G++) but as soon as it launches, it loads the first part of the progress bar then crashes.

All I could get from it was

`Setting vertical sync not supported
fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable
Logs will be displayed below. Log level is set to `silentcritical|warning`
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
BattleNetwork: ../../src/xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
`

I built it in debug mode, ran it with GDB, and none of those options offered any firther information on the issue. The XInitThreads seems to come from an X11 include, but after adding it to main.cpp the project is unable to build.

Setting the program to run in single threaded mode also did not fix the issue.

I switched from Windows to Linux due to it being easier to maintain than 6 separate and uncontrollable installs of Visual Studio, but I have not seen anything that would make the project not build against linux.

**Comment by TheMaverickProgrammer** [comment]
When you ran in single threaded you used `-s`? We have linux and mac users and no one else has had this issue with `-s`.

**Comment by 78Alpha** [comment]
I have reinstalled my OS and have changed to a different MESA driver version. I will rebuild to see if there is any issue still. Trying to find if it is a software issue, X11 issues, or that the hardware is "too new" to work nicely with Linux.

**Comment by 78Alpha** [comment]
Using Oibaf and not the AMD official helped out. The singlethreaded also wasn't working prior, as well as several compilation errors. It works at last, so I run and test. Hopefully I can switch to zig cc to cross compile for windows an the target ARM platform.
