### ISSUE TITLE
Make fallure on Linux

### ISSUE THREAD

**Issue by Lx32** [TheMaverickProgrammer/OpenNetBattle#224]
Hi, when I try to build the game on Linux but I get this error when I launch the make command.

`[ 30%] Built target sfml-graphics
[ 30%] Building CXX object CMakeFiles/BattleNetwork.dir/BattleNetwork/main.cpp.o
In file included from /home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/main.cpp:1:
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:158:27: error: declaration of ‘CardPackagePartitioner& Game::CardPackagePartitioner()’ changes meaning of ‘CardPackagePartitioner’ [-fpermissive]
  158 |   CardPackagePartitioner& CardPackagePartitioner();
      |                           ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnPackageManager.h:6,
                 from /home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:18,
                 from /home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/main.cpp:1:
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnScriptResourceManager.h:23:7: note: ‘CardPackagePartitioner’ declared here as ‘class CardPackagePartitioner’
   23 | class CardPackagePartitioner;
      |       ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/main.cpp:1:
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:159:29: error: declaration of ‘PlayerPackagePartitioner& Game::PlayerPackagePartitioner()’ changes meaning of ‘PlayerPackagePartitioner’ [-fpermissive]
  159 |   PlayerPackagePartitioner& PlayerPackagePartitioner();
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:49:7: note: ‘PlayerPackagePartitioner’ declared here as ‘class PlayerPackagePartitioner’
   49 | class PlayerPackagePartitioner;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:160:26: error: declaration of ‘MobPackagePartitioner& Game::MobPackagePartitioner()’ changes meaning of ‘MobPackagePartitioner’ [-fpermissive]
  160 |   MobPackagePartitioner& MobPackagePartitioner();
      |                          ^~~~~~~~~~~~~~~~~~~~~
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:51:7: note: ‘MobPackagePartitioner’ declared here as ‘class MobPackagePartitioner’
   51 | class MobPackagePartitioner;
      |       ^~~~~~~~~~~~~~~~~~~~~
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:161:28: error: declaration of ‘BlockPackagePartitioner& Game::BlockPackagePartitioner()’ changes meaning of ‘BlockPackagePartitioner’ [-fpermissive]
  161 |   BlockPackagePartitioner& BlockPackagePartitioner();
      |                            ^~~~~~~~~~~~~~~~~~~~~~~
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:50:7: note: ‘BlockPackagePartitioner’ declared here as ‘class BlockPackagePartitioner’
   50 | class BlockPackagePartitioner;
      |       ^~~~~~~~~~~~~~~~~~~~~~~
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:162:33: error: declaration of ‘LuaLibraryPackagePartitioner& Game::LuaLibraryPackagePartitioner()’ changes meaning of ‘LuaLibraryPackagePartitioner’ [-fpermissive]
  162 |   LuaLibraryPackagePartitioner& LuaLibraryPackagePartitioner();
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:52:7: note: ‘LuaLibraryPackagePartitioner’ declared here as ‘class LuaLibraryPackagePartitioner’
   52 | class LuaLibraryPackagePartitioner;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:168:19: error: declaration of ‘ConfigSettings& Game::ConfigSettings()’ changes meaning of ‘ConfigSettings’ [-fpermissive]
  168 |   ConfigSettings& ConfigSettings();
      |                   ^~~~~~~~~~~~~~
In file included from /home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnConfigReader.h:6,
                 from /home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnGame.h:9,
                 from /home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/main.cpp:1:
/home/dalmo/Giochi/native/OpenNetBattle/BattleNetwork/bnConfigSettings.h:16:8: note: ‘ConfigSettings’ declared here as ‘struct ConfigSettings’
   16 | struct ConfigSettings {
      |        ^~~~~~~~~~~~~~
cc1plus: note: unrecognized command-line option ‘-Wno-inconsistent-missing-override’ may have been intended to silence earlier diagnostics
make[2]: *** [CMakeFiles/BattleNetwork.dir/build.make:76: CMakeFiles/BattleNetwork.dir/BattleNetwork/main.cpp.o] Errore 1
make[1]: *** [CMakeFiles/Makefile2:206: CMakeFiles/BattleNetwork.dir/all] Errore 2
make: *** [Makefile:136: all] Errore 2
`

I use Pop_OS! 22.04 LTS.

**Comment by TheMaverickProgrammer** [comment]
Follow the error messages and try compiling with "-fpermissive" flag.

**Comment by Lx32** [comment]
I try to add the line CXXFLAGS='-fpermissive' at the make command but nothing changes

**Comment by TheMaverickProgrammer** [comment]
That should be all you need to do. Just clearing the cache and re-configuring the project with that flag set. Otherwise this is #development branch which is the on-going branch for new features. You'll have to be a programmer and fiddle with things to get it to work flawlessly on Linux atm. If you just want to play the game, join the discord.
